### ISSUE TITLE
Please link to old docs?

### ISSUE THREAD

**Issue by rashkov** [reason-association/rescript-lang.org#102]
Could we please link to the old docs at https://bucklescript.netlify.app/ ? As a kindness for people who are still on versions of Bucklescript older than 8.0.0. The company where I work is doing our best to migrate to 8.0.0 but we're not there yet. No one on my team knew how to find the old docs, and the only reason I knew is because I asked on the Discord channel. It shouldn't be that hidden. Please, for the sake of long time bucklescript users, can we support the old docs a little?

**Comment by jfrolich** [comment]
I am interested why you are still < 8.0. There have been very few breaking changes.

**Comment by ryyppy** [comment]
this sounds like you are actually on BS v5. What prevents you from upgrading?

**Comment by rashkov** [comment]
withstyles ppx from an old version of bs-material-ui

**Comment by ryyppy** [comment]
The v8 docs are pretty much just the v7 docs, the v7 docs are what you see on the unofficial bucklescript netlify deployment you posted above.

What kind of information are you missing on the v8.0.0 docs in particular? bs.deriving?

**Comment by rashkov** [comment]
Appreciate the response... I didn't realize that's the only difference between v8.0.0 docs and older. Yes, bs.deriving was missing and that made me completely doubt the completeness of the docs. If that's really the only difference then this issue is much smaller than I realized, and I feel a lot better about the docs situation.

I do think bs.deriving warrants inclusion, and I still think it's very jarring to see that anything older than v8.0.0 is unacknowledged and unavailable, like it never existed. The fact that v8 docs can be used for v7 is good to know, but not at all obvious without having closely followed the releases, and it was easy for me to think that there was more lost in the rebrand to rescript.

**Comment by schutm** [comment]
I'm missing the ocaml syntax... I understand you're moving away from the ocaml syntax. However sticking even on older version would not be sensible if the documentation is taken away (and yes, I'm using taking advantage of both compiling with bucklescript and the ocaml compiler itself).

However removing the documentation completely, makes wonder whether sticking with rescript/reason/bucklescript is a viable option for the future.

**Comment by chenglou** [comment]
@rashkov your concern is legit but as Patrick said, most of the content is still there. We'll make this a bit less scary by changing the dropdown option of `8.0.0` to `< 8.2.0`

`bs.deriving` can be added back. Would you mind providing a rough list of things you found missing? (Use the search to check if it's there)

**Comment by yawaramin** [comment]
Maybe this is already on the radar but thought I'd mention, the `Node` API docs are unavailable.

**Comment by jsiebern** [comment]
@rashkov Sorry you're having update troubles with the ppx. Feel free to contact me on discord (`Jonathan#2836`) or DM me on twitter (`@j_siebern`) and I'll be happy to help you upgrade to the latest version.

**Comment by ryyppy** [comment]
I changed the way versions are being displayed on the docs (see #112) to make it more clear that the `< 8.2.0` are supposed to cover the original BuckleScript website in its fullest.

Since there are some features missing, please let us know in #113 what kind of information you are relying on.

**Comment by rashkov** [comment]
Thanks everyone!
