### ISSUE TITLE
Playground doesn't load (403 from jsdelivr)

### ISSUE THREAD

**Issue by yorickvP** [reason-association/rescript-lang.org#116]
Tried to show the playground to someone, but they didn't have it cached. It failed to load with a 403:

403: GET https://cdn.jsdelivr.net/gh/ryyppy/bs-platform-js-releases@latest/VERSIONS
> Package size exceeded the configured limit of 50 MB. Try https://github.com/ryyppy/bs-platform-js-releases/tree/master/VERSIONS instead.

**Comment by ryyppy** [comment]
Thanks for the report. Will need to change our hosting provider to prevent this kind of issues in the future.

Created a topic on our forum to keep track of the status: https://forum.rescript-lang.org/t/playground-cdn-issues/672

**Comment by ryyppy** [comment]
Fixed in #117
