### ISSUE TITLE
Reserved keywords in docs are not up to date

### ISSUE THREAD

**Issue by amiralies** [reason-association/rescript-lang.org#119]
it seems some names are marked as keyword by mistake, ie class related keywords, `struct` `sig` etc.

**Comment by ryyppy** [comment]
You mean in the `<8.2.0` docs? Sadly this is not a mistake. In Reason, you need to treat all OCaml keywords also as Reason keywords, due to the "being 100% OCaml" syntax constraint.

**Comment by amiralies** [comment]
You're right I thought i was looking at latest docs.
