### ISSUE TITLE
Include %obj() in the Object Creation documentation 

### ISSUE THREAD

**Issue by kevanstannard** [reason-association/rescript-lang.org#130]
Would it be worth including an example of using `%obj()` in the section on [Object Creation](https://rescript-lang.org/docs/manual/latest/object#creation)?

Edit: It's used in examples in the API docs, but not sure if it was intentionally omitted from the main docs or not. Thanks.

**Comment by ryyppy** [comment]
Can you point me to the API docs?

I am pretty sure the `%obj()` syntax is obsolete for ReScript code, because we have dedicated JS object syntax for that.

**Comment by kevanstannard** [comment]
Hi @ryyppy, it's currently used in a couple of spots in the example for `assign`

https://rescript-lang.org/docs/manual/latest/api/js/obj#assign

**Comment by kevanstannard** [comment]
I've created a small PR to update those examples:

https://github.com/reason-association/rescript-lang.org/pull/138

**Comment by ryyppy** [comment]
Fixed in #138
