### ISSUE TITLE
OCaml syntax on error messages

### ISSUE THREAD

**Issue by jchavarri** [reason-association/rescript-lang.org#140]
https://rescript-lang.org/try?code=DYUwLgBGBcHAlgZzAHmQJ3gOwOYD4IBeCACgEYAaCAJgEoBuIA

Compiling in https://rescript-lang.org/try with `.res` syntax.

Input code:
```
let t: list<string> = (1, 2);
```

Error message:
```
[E] Line 1, column 22:

This has type:
    'a * 'b
  But somewhere wanted:
    string list
```

Expected:

```
[E] Line 1, column 22:

This has type:
    ('a, 'b)
  But somewhere wanted:
     list<string>
```

Can't reproduce when compiling code with `bsb`.

**Comment by ryyppy** [comment]
Fixed in #143
