### ISSUE TITLE
Add note on External regarding interface files

### ISSUE THREAD

**Issue by ryyppy** [reason-association/rescript-lang.org#159]
When writing externals for JS code, it is rather easy to unintentionally introduce extra code by not using the same external in the interface (`.resi`) file. Therefore, whenever you are exposing an external, you need to make sure to copy the same external to your interface file to guarantee zero-cost bindings.

We previously had a note in the old docs that state

>Note: do also use externals and the [@bs.blabla] attributes in the interface files. Otherwise the inlining won't happen.

This is an important note, so it should be added back to the [External](https://rescript-lang.org/docs/manual/latest/external) page.

**Comment by jfrolich** [comment]
It would actually be super amazing if the compiler becomes a little smarter and will inline it anyway. But that might be pretty hard to do. (the overhead of this in native is tiny, but in JS it the difference between zero-cost and another function call.)
