### ISSUE TITLE
Document @deprecated decorator

### ISSUE THREAD

**Issue by ryyppy** [reason-association/rescript-lang.org#168]
Probably should be put in the [Attribute (Decorator) section](https://rescript-lang.org/docs/manual/latest/attribute#usage)

**Comment by bdunn313** [comment]
Got one out in the wild for this one. I could see taking a different approach here by having a section specifically on deprecation and how language server integrations can show them as having a strikethrough etc like in the vscode extension, but I figured that route should be discussed first.

This is the basic implementation where it's just added as another example to the existing block of attribute examples.
