### ISSUE TITLE
Dom module documentation not accessible

### ISSUE THREAD

**Issue by yawaramin** [reason-association/rescript-lang.org#18]
The following link: https://bucklescript.github.io/bucklescript/api/Dom.html

Redirects to: https://rescript-lang.org/apis/latest

Which does not have the `Dom` module available.

**Comment by ryyppy** [comment]
Yep we'll tackle that as soon as we made sure that Reason v3.6 users can use our docs properly

**Comment by ryyppy** [comment]
Fixed in #34 
You can find the docs here: https://rescript-lang.org/apis/latest/dom
