### ISSUE TITLE
highlight.js dependency EOL

### ISSUE THREAD

**Issue by bdunn313** [reason-association/rescript-lang.org#188]
According to the depreciated message during installation, highlight.js@9 is at EOL. Example output from a recent `npm install`:

```bash
$ npm install
...
> highlight.js@9.18.5 postinstall /home/brad/OpenSource/rescript-lang.org/node_modules/highlight.js
> node deprecated.js

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

  Verion 9 of Highlight.js has reached EOL.  It will no longer
  be supported or receive security updates in the future.
  Please upgrade to version 10 or encourage your indirect
  dependencies to do so.

  For more info:

  https://github.com/highlightjs/highlight.js/issues/2877
  https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md

-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
```

Upgrade guide can be found here:
https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_UPGRADE.md

**Comment by bdunn313** [comment]
I think that this might still be a legit issue, but I misunderstood that this project uses yarn and not npm. Got confused! Example might be a bit misleading.

**Comment by ryyppy** [comment]
wanna give it a shot and try to upgrade it? 😄
Our hljs usage is pretty self sustained (grammars are located in the plugins folder), so shouldn't be too hard to raise the dependency.

**Comment by bdunn313** [comment]
Yeah, I can take this on when I have some time!
