### ISSUE TITLE
Array destructuring example in docs results in JS error after compilation

### ISSUE THREAD

**Issue by thepeoplesbourgeois** [reason-association/rescript-lang.org#203]
I'm unsure of how to categorize this one. It definitely feels like a bug, given the documentation, but I'm almost certain it's a feature, given how strict the language seems as a whole.

The concerned section of documentation…

> Destructuring works with most built-in data structures:
>
> ```reason
> ...
>
> // Array
> let myArray = [1, 2, 3]
> let [item1, item2] = myArray // 1 assigned to `item1`, 2 assigned to `item2`
> 
> ...
> ```

… with the corresponding JS output, already declaring that it will fail:

> ```js
> var myArray = [1, 2, 3];
> if (myArray.length !== 2) {
>   throw {
>     RE_EXN_ID: "Match_failure",
>     _1: [
>       "playground.res",
>       14,
>       4
>     ],
>     Error: new Error()
>   };
> }
> var item1 = myArray[0];
> var item2 = myArray[1];
> ```

Indeed, plugging this output directly into console, unsurprisingly, returns the error:

```js
Uncaught Object { RE_EXN_ID: "Match_failure", _1: (3) […], Error: Error }
  <anonymous> debugger eval code:12
```

I installed `bs-platform` and cloned the `rescript-project-template` repo, in case there was some error handler in the larger BS platform that the [playground](https://rescript-lang.org/try) was abstracting away, but it was to no avail:

```sh
$ cat src/Demo.res
let myArr = [1,2,3]
let [one, two] = myArr

Js.log2(one, two)

$ node src/Demo.bs.js 

/Users/newb/workspace/javascript/rescript-tryout/src/Demo.bs.js:12
  throw {
  ^
{
  RE_EXN_ID: 'Match_failure',
  _1: [ 'Demo.res', 2, 4 ],
  Error: Error
      at Object.<anonymous> (/Users/newb/workspace/javascript/rescript-tryout/src/Demo.bs.js:19:16)
      at Module._compile (node:internal/modules/cjs/loader:1108:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
      at Module.load (node:internal/modules/cjs/loader:973:32)
      at Function.Module._load (node:internal/modules/cjs/loader:813:14)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
      at node:internal/main/run_main_module:17:47
}
```

It seems as if this example might have been valid BS in an earlier version of the language, but has since changed from emitting a warning at compile/runtime, to emitting a (bewilderingly cryptic) warning at compile time (`You forgot to handle a possible case here, for example: [| |]`) and throwing an uncaught error at runtime.

It likely would be best to remove the example from the docs, so as to not give newcomers the impression that partial array destructuring is possible in ReScript the same way it is in JavaScript.

**Comment by kevanstannard** [comment]
Looks like this is related to #198

**Comment by jfrolich** [comment]
Your example only matches an array with exactly 2 items, this is why it is crashing (there are three items in the array). It does not behave the same as JS-destructuring.

**Comment by chenglou** [comment]
Thanks, fixed
