### ISSUE TITLE
A broken link in BS_VSCODE example

### ISSUE THREAD

**Issue by zainfathoni** [reason-association/rescript-lang.org#21]
[The link](https://github.com/rescript-lang/rescript-compiler/blob/master/jscomp/bsb/templates/basic-reason/.vscode/tasks.json#L6) to a [BS_VSCODE usage example](https://rescript-lang.org/docs/manual/latest/build-configuration#bs_vscode-error-output-adapted-for-vscode) is broken due to its removal in this https://github.com/rescript-lang/rescript-compiler/pull/4187 PR

**Comment by chenglou** [comment]
Thanks!
