### ISSUE TITLE
Is there a way to access object's fields using a variable (string) as key ? 

### ISSUE THREAD

**Issue by mdubourg001** [reason-association/rescript-lang.org#220]
Hey there ! First, great job with ReScript ! 👍 

I'm trying to read the `dependencies` field of a `package.json` file and to iterate on its keys. As I do not known which keys will be in my `dependencies` object, I'm typing it `'a`. But I can't figure out how to access the value corresponding to each key while iterating:

```rescript
@bs.val external __dirname: string = "__dirname"

@bs.module("fs")
external readFileSync: (string, string) => string = "readFileSync"

@bs.scope("JSON") @bs.val
external parseJSON: string => 'a = "parse"

let package = readFileSync(`${__dirname}/package.json`, "utf8")
let parsed = parseJSON(package)
let dependencies = parsed["dependencies"]

Js.Obj.keys(dependencies)->Js.Array2.forEach(name => Js.Log(dependencies[name])) // <-- the error happens here
``` 

I get the following error on `dependencies[name]`:

```
This has type: string
Somewhere wanted: int
  
You can convert string to int with Belt.Int.fromString.
``` 

Is there any way to do such a thing ?

**Comment by kevanstannard** [comment]
Hi @mdubourg001 you might like to post questions like these on the [ReScript forum](https://forum.rescript-lang.org/) where more people will see it. This issue tracker is for issues with the rescript-lang.org site.

Regarding your question, a quick version may be something like this:

```res
type package = {dependencies: Js.Dict.t<string>}

@bs.module external package: package = "../package.json"

Js.Dict.keys(package.dependencies)->Js.Array2.forEach(name => {
  Js.log(name)
})
```

But you may get better solutions from others on the forum.

**Comment by mdubourg001** [comment]
Oh I'm sorry, I did not know there was a forum, I'll post my question there.

Anyway, thanks for your fast answer. 👌
