### ISSUE TITLE
Javascript issues on Firefox + noscript

### ISSUE THREAD

**Issue by sapristi** [reason-association/rescript-lang.org#53]
Hello, 
I have issues opening any page on https://rescript-lang.org/ on Firefox. I guess the issue is related with the noscript extension.
When opening the page, I briefly see the content, then the page goes blank, and the "A webpage is slowing down your browser" banner appears.
The console is spammed with the following error : 
```
TypeError: o.apply is not a function
    NextJS 57
```

After stopping Js execution and opening the NoScript panel, the site went fine after activating scripts from `jsdeliver.net`

**Comment by ryyppy** [comment]
I don't know the noscript extension...any technical details on what it does with the browser environment?

**Comment by sapristi** [comment]
In short, NoScript allows to block the loading of javascript files by host (for each website)

Here's what's going on in github e.g:
![image](https://user-images.githubusercontent.com/901257/94480476-a6eb4e00-01d6-11eb-80dc-5f3d3edcd206.png)

It is expected that a website can be broken somehow when scripts from a certain host are blocked, but it is the first time I encounter a website that actively crashes in this case.

But it seems the issue is fixed by now, thank you !

**Comment by ryyppy** [comment]
Yeah, a Next app does a lot of code splitting and loads artifacts from their edge network, so it might be that some client code tries to load and execute some modules after initialisation, which may cause a crash if the code is not available due to blocker software.

Good it is fixed now! Thanks for the explanations.
