### ISSUE TITLE
Wrong vscode extension

### ISSUE THREAD

**Issue by amiralies** [reason-association/rescript-lang.org#57]
editor page in 8.2 docs points to [reason-vscode](https://marketplace.visualstudio.com/items?itemName=jaredly.reason-vscode)  which doesn't contain rescript syntax anymore

**Comment by jameslan** [comment]
Should be [rescript-vscode](https://marketplace.visualstudio.com/items?itemName=chenglou92.rescript-vscode) I think

**Comment by ryyppy** [comment]
Fixed on master. Thanks!
