### ISSUE TITLE
Difficult to find where to report issues from rescript-lang.org

### ISSUE THREAD

**Issue by vasco3** [reason-association/rescript-lang.org#63]
When browsing rescript-lang.org is hard to figure out where to report issues like broken links and typos.

Currently I clicked on the github link in the top right and navigates to [ReScript Github profile](https://github.com/rescript-lang)
<img width="231" alt="image" src="https://user-images.githubusercontent.com/804301/94169937-b5acca80-fe8f-11ea-97fb-ea049e94ef71.png">

I would expect to find the repo for rescript-lang.org there, so I can open a github issue. So then I had to search until I found that this repo was under the reason-association.

I suggest placing an easy call to action for reporting issues

**Comment by bobzhang** [comment]
cc @ryyppy I had similar issues

**Comment by ryyppy** [comment]
fixed on master
