### ISSUE TITLE
Sort api functions in alphabetical order

### ISSUE THREAD

**Issue by ryyppy** [reason-association/rescript-lang.org#69]
See https://forum.rescript-lang.org/t/how-to-use-js-belt-set-belt-map-dict/432/7?u=ryyppy

**Comment by chenglou** [comment]
This isn't 100% possible at least, if only because the items have a dependency on each other. But we can keep this in mind

**Comment by jfrolich** [comment]
It would be possible to sort them just in the docs? (not in the `mli` file). Reasoning is that the dependency doesn't matter for the consumer of the API. I think it's also more readable if submodules, values/functions and types are separate sections in the docs.

**Comment by ryyppy** [comment]
yes that's something i'd like to have soon. The only thing needed to make this work is adding the sorting logic in the extract–indices script ((here)(https://github.com/reason-association/rescript-lang.org/blob/master/scripts/extract-indices.js))

just a matter of opening your local docs, adjust the logic, run the script and check the docs again

**Comment by ryyppy** [comment]
Fixed with #161
