### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by theqp** [reason-association/rescript-lang.org#72]
Hello

In this file, the documentation is incorrect regarding JavaScript "Integer Division/Multiplication".
https://github.com/reason-association/rescript-lang.org/blob/cfb9ea89d3d42fee1ce3e8e67e76dd82e0fa49b1/pages/docs/manual/latest/overview.mdx

It states that in JavaScript `2 / 23 * 1` is integer division, but it is not.

**Comment by ryyppy** [comment]
> It states that in JavaScript 2 / 23 * 1 is integer division, but it is not.

What is the correct statement?

**Comment by theqp** [comment]
@ryyppy 
The correct statement is

```
var Caml_int32 = require("./stdlib/caml_int32.js");
Math.imul(Caml_int32.div(2, 23), 1)
```

Here is my proof: https://rescript-lang.org/try?code=DYUwLgBAJglgbhAvBAFAQwFwRgOzAGggCMtcCIBjUvASiQD5iIB6CNCAKkoCgg

**Comment by theqp** [comment]
Same is true for integer addition

https://rescript-lang.org/try?code=DYUwLgBAJglgbhAvBAFAQwFwRgOzAGggCMtcwBKJAPgjQgGpig

**Comment by ryyppy** [comment]
the goal of this comparison page is not to be 100% accurate on the compile output, but to give an overview on what how JS / ReScript constructs compare on the syntax surface

**Comment by theqp** [comment]
@ryyppy then I suggest removing integer operations (Division/Multiplication, Addition) because there are no integers in JavaScript.

**Comment by chenglou** [comment]
Thanks! We can't not document the integer calculations there as it'd raise more questions. I've added a disclaimer after the table though
