### ISSUE TITLE
Document syntax for `module type of`

### ISSUE THREAD

**Issue by sapristi** [reason-association/rescript-lang.org#74]
Hello,
this issue is just a reminder that some documentation about `module type of` (cf https://caml.inria.fr/pub/docs/manual-ocaml/moduletypeof.html) would be welcome.
I could find an example usage here: https://github.com/rescript-lang/rescript-compiler/issues/2765

Cheers,

**Comment by ryyppy** [comment]
Hmm, not sure where to put this... probably somewhere near the [Extending Modules](https://rescript-lang.org/docs/manual/latest/module#extending-modules) section

**Comment by sapristi** [comment]
Well I can see that an example was added in the doc, so I guess we can close this ?
https://rescript-lang.org/docs/manual/latest/module#extending-module-signatures

**Comment by ryyppy** [comment]
right, i think this was actually already there? will close it then.
