### ISSUE TITLE
Add reason syntax to latest version docs

### ISSUE THREAD

**Issue by amiralies** [reason-association/rescript-lang.org#89]
I believe the best way to use rescript atm is using reason syntax. since it's more mature and has a greater editor support.
don't get me wrong I like rescript syntax (I even wrote small [vim syntax](https://github.com/amiralies/vim-rescript) for it) and appreciate all the work done behind the scene to move to new syntax (especially the work done by @IwanKaramazow for parser) but the new syntax still needs a bit more time to be more mature and polished (there are some bugs occasionally and it's getting better by adding more features).
it makes adoption a bit harder, people don't want to use a language with immature parser and w/o editor support, I think prioritizing rescript syntax in the docs atm makes people feel using it is the best option and reason syntax is not supported in newer versions.

**Comment by ryyppy** [comment]
We are not far off shipping the editor tooling, and last bugs are getting squashed as our user base is growing.

Staying on the old syntax is not recommended, and encouraging new users to use the old syntax will make it harder for us to move forward. Even rescript-lang.org has fully migrated to ReScript syntax now.

During this transition phase we will continue to refer Reason users to the `< 8.2.0` docs, maybe we'll make it a little bit more obvious for our users to find those docs.

**Comment by amiralies** [comment]
Yeah we are close to ship editor tooling and maybe my argument about editor tooling is not valid anymore.
I'm not really strict about adding resaon syntax to latest version docs.IMO it shows users that they can use a more mature syntax (bugs like https://github.com/rescript-lang/syntax/issues/163 can be a turn off while you are adopting a new language) but yeah adding reason might add another level of complexity, maintenance issues and confusion. I'm closing this for now.
