### ISSUE TITLE
A misspoke in the Pattern Matching doc

### ISSUE THREAD

**Issue by DZakh** [reason-association/rescript-lang.org#90]
In the [complex example](https://rescript-lang.org/docs/manual/latest/pattern-matching-destructuring#complex-examples) there is a comment:
```js
// this is matched only if `name` isn't "Joe"
```
Although it should be something like:
```js
// this is matched only if `name` isn't "Mary" or "Joe"
```

**Comment by ryyppy** [comment]
You are right. You can open a PR for these kind of fixes since they are pretty easy to review
